<?php
namespace McShop\ServersBundle\Repository;

use Doctrine\ORM\EntityRepository;
use McShop\ServersBundle\Entity\Server;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{
    /**
     * @return Server[]
     */
    public function findAll()
    {
        $qb = $this->createQueryBuilder('s');

        return $qb
            ->select('s')
            ->leftJoin('s.cache', 'c')
            ->getQuery()
            ->execute()
        ;
    }
}
