<?php

namespace McShop\ServersBundle\Repository;

/**
 * ServerCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerCacheRepository extends \Doctrine\ORM\EntityRepository
{
}
