<?php

namespace McShop\PexBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PexEntityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PexEntityRepository extends EntityRepository
{
}
