<?php

namespace McShop\PexBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * PexInheritanceRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PexInheritanceRepository extends EntityRepository
{
    public function getUsersForGroup($groupName)
    {
        $qb = $this->createQueryBuilder('pi');
        $users = $qb
            ->select('u')
            ->join('McShopUserBundle:User', 'u', Join::WITH, 'u.uuid = pi.child')
            ->where('pi.parent = :parent')
            ->setParameter('parent', $groupName)
            ->getQuery()
            ->getResult(AbstractQuery::HYDRATE_OBJECT)
        ;

        return $users;
    }
}
