<?php

namespace McShop\PexBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PexPermissionsRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PexPermissionsRepository extends EntityRepository
{
}
