<?php

namespace McShop\ShoppingCartBundle\Repository;

/**
 * BuyHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
