<?php

namespace McShop\ShoppingCartBundle\Repository;

/**
 * BuyHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function getTotalCount()
    {
        $qb = $this->createQueryBuilder('bh');

        return $qb->select('COUNT(bh)')->getQuery()->getSingleScalarResult();
    }
}
