<?php
namespace McShop\ShoppingCartBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * ShoppingCartCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingCartCategoryRepository extends NestedTreeRepository
{
}
