<?php
namespace McShop\ShoppingCartBundle\Repository;

/**
 * StorefrontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingCartItemRepository extends \Doctrine\ORM\EntityRepository
{
}
