<?php
namespace McShop\ShoppingCartBundle\Repository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Component\Form\Test\FormInterface;

/**
 * StorefrontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingCartItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Pagerfanta
     */
    public function findAllAsPagination(FormInterface $form = null)
    {
        $qb = $this->createQueryBuilder('i');
        $qb
            ->select('i, c, s')
            ->leftJoin('i.category', 'c')
            ->innerJoin('i.server', 's')
        ;

        if ($form !== null) {
            //todo: some filter logic
        }

        $adapter = new DoctrineORMAdapter($qb);
        $pagination = new Pagerfanta($adapter);

        return $pagination;
    }
}
