<?php
namespace McShop\ShoppingCartBundle\Repository;
use Doctrine\ORM\EntityRepository;
use McShop\ShoppingCartBundle\Entity\ShoppingCartCategory;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\Test\FormInterface;

/**
 * StorefrontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingCartItemRepository extends EntityRepository
{
    /**
     * @param ShoppingCartCategory[]|null $categories
     * @param Form $form
     * @return Pagerfanta
     */
    public function findAllAsPagination(array $categories = [], Form $form = null)
    {
        $qb = $this->createQueryBuilder('i');
        $qb
            ->select('i, c, s')
            ->leftJoin('i.category', 'c')
            ->innerJoin('i.server', 's')
        ;

        if (count($categories) > 0) {
            $qb->andWhere('i.category IN (:categories)')
                ->setParameter('categories', $categories)
            ;
        }

        if ($form !== null) {
            //todo: some filter logic
        }

        $adapter = new DoctrineORMAdapter($qb);
        $pagination = new Pagerfanta($adapter);

        return $pagination;
    }
}
