<?php

namespace McShop\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use McShop\UserBundle\Entity\Token;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
    public function findTokenByValue($value)
    {
        $qb = $this->createQueryBuilder('t');
        /** @var Token|null $token */
        $token = $qb->select('t,u')
            ->innerJoin('t.user', 'u')
            ->where('t.value = :value')
            ->setParameter('value', $value)
            ->getQuery()
            ->getOneOrNullResult()
        ;

        if ($token === null || !$token->getActive()) {
            return false;
        }

        return $token;
    }
}
