<?php

namespace McShop\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use McShop\UserBundle\Entity\User;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Form\Form;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    /**
     * @inheritdoc
     */
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->leftJoin('u.roles', 'r')
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param Form|null $form
     * @return User[]|Pagerfanta
     */
    public function getAllPaginated(Form $form = null)
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->select('u, r, p')
            ->leftJoin('u.roles', 'r')
            ->leftJoin('u.purse', 'p')
            ->orderBy('u.id', 'DESC')
        ;

        if ($form !== null && $form->get('username')->getData() !== null) {
            $qb
                ->where('u.username LIKE :username')
                ->setParameter('username', '%' . $form->get('username')->getData() . '%')
            ;
        }

        $adapter = new DoctrineORMAdapter($qb);
        $pagination = new Pagerfanta($adapter);

        return $pagination;
    }
}
