<?php

namespace McShop\StaticPageBundle\Repository;

use Doctrine\ORM\EntityRepository;
use McShop\StaticPageBundle\Entity\Page;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * @param $slug
     * @return Page|null
     */
    public function findOneBySlug($slug)
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->select('p, u, r')
            ->innerJoin('p.user', 'u')
            ->leftJoin('p.role', 'r')
            ->where('p.slug = :slug')
            ->setParameter('slug', $slug)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
