<?php

namespace McShop\StaticPageBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use McShop\StaticPageBundle\Entity\Page;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    const RETURN_QUERY = 0;
    const RETURN_RESULT = 1;

    /**
     * @param $slug
     * @return Page|null
     */
    public function findOneBySlug($slug)
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->select('p, u, r')
            ->innerJoin('p.user', 'u')
            ->leftJoin('p.role', 'r')
            ->where('p.slug = :slug')
            ->setParameter('slug', $slug)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    /**
     * @return Page[]|QueryBuilder|null
     */
    public function findAll($returnType = self::RETURN_RESULT)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->select('p, u, r')
            ->innerJoin('p.user', 'u')
            ->leftJoin('p.role', 'r')
        ;

        if ($returnType === self::RETURN_QUERY) {
            return $qb;
        }

        if ($returnType === self::RETURN_RESULT) {
            return $qb->getQuery()->execute();
        }

        return null;
    }

    /**
     * @return Page[]|null
     */
    public function findAllForMenu()
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->select('p, u, r')
            ->innerJoin('p.user', 'u')
            ->leftJoin('p.role', 'r')
            ->where('p.showInMenu = :bool')
            ->setParameter('bool', true)
            ->getQuery()
            ->execute()
        ;
    }
}
